language: php

dist: bionic

php:
  - 8.2
  - 8.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer config -g github-oauth.github.com $CI_USER_TOKEN
  - phpenv config-rm xdebug.ini || true

install:
  - travis_retry composer install

script:
  - vendor/bin/phpunit
